### ISSUE TITLE
Replace `publishing` with `withTopics`

### ISSUE THREAD

**Issue by ignasi35** [lagom/lagom-java.g8#13]
Lagom `1.3.6` ~deprecates~ _may deprecate_ `publishing` in favor of `withTopics` on the javadsl `Descriptor`.

When `1.3.6` is out, this `g8` template ~needs~ _may need_ updating.

(edit: updated tense)

**Comment by rcavalcanti** [comment]
Will it be 1.3.6 or 1.4.0? 

If 1.3.6, I guess we need `backporting` for https://github.com/lagom/lagom/pull/823

**Comment by ignasi35** [comment]
I was assuming that `1.3.6` will include the deprecation warning and the `withTopics` alternative. In that scenario I think this template should use the non-deprecated method.
